### ISSUE TITLE
goToStepNumber() not working in v6.0.0

### ISSUE THREAD

**Issue by renakollmannsuhr** [usablica/intro.js#1770]
## Description

goToStepNumber(num) function is not working on version 6 like it did with version 5.1.
How would I go to a specific step number in version 6? Is anyone else having this issue?

## Expected Behavior
Expected to start tour at the specified step number using version 6 intro.js.

## Actual Behavior
Recieved error: _Uncaught TypeError: introJs(...).setOptions(...).goToStepNumber(...).start is not a function)_

And the tour would not start.

## Example (recommended)

In a test app using intro.js version 5.1 I was able to initiate a tour with:
introJs().setOptions({
steps:[ .....]}).goToStepNumber(num).start();

I also added the data-step='' attributes to the specified elements.

However the same code in version 6 resulted in an error.

**Comment by iubkud** [comment]
Just ran into this, the same workaround here seemed to work for me https://github.com/usablica/intro.js/issues/465

Try `introJs.setOptions({steps: [...]}).start().goToStepNumber(num);` instead

**Comment by iubkud** [comment]
I ran into the same issue. I was able to get it working by instead doing this:

```
let intro = introJs.setOptions({ steps: [...] });
intro.start();
intro.goToStepNumber(num);
```

Hope that helps.

**Comment by renakollmannsuhr** [comment]
@iubkud That workaround does it for me. Thanks!

**Comment by afshinm** [comment]
This is expected and is because `goToStepNumber` is an `async` function now, which doesn't return an `IntroJS` object and instead, it returns `Promise<IntroJS>`. See https://github.com/usablica/intro.js/blob/master/src/index.js#L207-L211

**Comment by banagale** [comment]
I also had this problem. I've opened [a PR](https://github.com/usablica/introjs-website/pull/175/commits/075be960fb973781fe36891e36ae530b2f0027cd) on the docs to address this.
